# Generated by Django 3.1 on 2020-08-26 14:03

from django.db import migrations, models
import practice.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userEmail', models.EmailField(max_length=30, primary_key=True, serialize=False, verbose_name='이메일(아이디)')),
                ('nickName', models.CharField(max_length=12, verbose_name='닉네임')),
                ('password', models.CharField(max_length=12, verbose_name='비밀번호')),
                ('registerDate', models.DateField(auto_now_add=True, verbose_name='가입시간')),
                ('photo', models.FileField(blank=True, upload_to=practice.models.date_upload_to)),
                ('guardianName', models.CharField(blank=True, max_length=12, verbose_name='보호자명')),
                ('guardianCallNum', models.CharField(blank=True, max_length=12, verbose_name='보호자전화번호')),
                ('guardianBasicMsg', models.CharField(blank=True, max_length=100, verbose_name='보호자기본메세지')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='nickName',
        ),
    ]
